states = ['Тайланд', 'Китай', 'Индия', 'Сирия', 'Иран', 'Индонезия']
print(states)
print(sorted(states))
print(states)
print(sorted(states, reverse=True))
print(states)
states.reverse()
print(states)
states.reverse()
print(states)
states.sort()
print(states)
states.sort(reverse=True)
print(states)
